"""The charges against Jeanne d'Arc, the Twelve Articles and the verdict of the
University of Paris, March-May 1431, from Jules Quicherat, Procès de
condamnation et de réhabilitation de Jeanne d'Arc, vol. I (Paris 1841).

Internet Archive procsdecondam01joanuoft; printed page n = image n+15. The OCR
was used to find the places; every excerpt was read against the page images.
Quicherat's text is kept; cuts are marked [...].

English: the site's working translation (CC0).

Each unit: pg (Quicherat page), titel, orig, en, note."""

CHARGES = [
 {"pg": "203–204",
  "titel": "What the promoter asked the judges to declare",
  "orig": "[...] ad finem seu fines quod quædam mulier, Johanna la Pucelle vulgariter nuncupata, [...] per vos, præfatos judices, pronuncietur et declaretur sorceria sive sortilega, divinatrix, pseudo-prophetissa, malignorum spirituum invocatrix et conjuratrix, superstitiosa, et magicis artibus implicita ac insistens, male sapiens in et de fide nostra catholica, schismatica, in articulum Unam sanctam, etc. ipsiusque fidei nonnullos alios articulos, dubia atque devia, sacrilega, idolatra, apostatrix a fide, maledica ac malefica, in Deum et Sanctos suos blasphema, scandalosa, seditiosa, turbativa pacis et ejus impeditiva, excitatrix ad bella, sanguinis humani crudeliter sitibunda, et ad ipsius effusionem incitatrix, sexus sui decentiam atque congruentiam sine verecundia penitus derelinquens, et deformem habitum statumque virorum armatorum inverecunde assumens; circa hæc et alia apud Deum et homines abominabilis, legum divinæ et naturalis atque ecclesiasticæ disciplinæ prævaricatrix, principum et popularium seductrix; permittendo et consentiendo in contumeliam et contemptum Dei se venerari et adorari, manus suas et vestes osculandas exhibendo, divini honoris atque cultus usurpatrix; hæretica aut saltem de hæresi vehementer suspecta; ac super his, juxta et secundum divinas et canonicas sanctiones, canonice ac legitime puniatur atque corrigatur [...]: dicit, proponit ac probare intendit [...] Johannes de Estiveto, ecclesiarum Bajocensis et Belvacensis canonicus, promotor seu procurator officii vestri [...].",
  "en": "[...] to the end that a certain woman, commonly called Jeanne the Maid, [...] be pronounced and declared by you, the said judges, a sorceress or witch, a diviner, a false prophetess, an invoker and conjurer of evil spirits, superstitious, involved and persisting in magic arts, thinking wrongly in and of our catholic faith, schismatic against the article Unam sanctam etc., doubtful and astray on several other articles of that faith, sacrilegious, idolatrous, an apostate from the faith, a slanderer and evildoer, a blasphemer against God and his saints, scandalous, seditious, a disturber and hinderer of peace, an inciter to wars, cruelly thirsting for human blood and inciting to its shedding, wholly abandoning without shame the decency and fitness of her sex, and shamelessly taking the misshapen dress and state of men-at-arms; for these and other things abominable to God and men, a transgressor of divine and natural law and of the Church's discipline, a seducer of princes and peoples; who allowed and consented, to the insult and contempt of God, to be venerated and adored, offering her hands and clothes to be kissed, a usurper of divine honour and worship; heretical, or at least vehemently suspect of heresy; and that for these things she be canonically and lawfully punished and corrected according to divine and canonical law [...]: so says, proposes and intends to prove [...] Jean d'Estivet, canon of the churches of Bayeux and Beauvais, promoter or proctor of your office [...].",
  "note": "The preamble of the promoter's libel of seventy articles, read to Jeanne on 27–28 March 1431. Jean d'Estivet, called Benedicite, was the prosecutor; he had followed Cauchon from Beauvais. The list is the whole case in one sentence: witchcraft, false prophecy, schism, idolatry, war, and the dress of men-at-arms. Most of it was dropped when the seventy articles were reduced to twelve."},
]

TWELVE = [
 {"pg": "328–330",
  "titel": "Article I: the voices, the tree of the fairies, the Church Militant",
  "orig": "« Et primo, quædam fœmina dicit et affirmat quod, dum esset ætatis annorum tredecim vel eocirca, ipsa suis oculis corporalibus vidit sanctum Michaelem eam consolantem, et quandoque sanctum Gabrielem, in effigie corporali apparentes. [...] Quodque prædictæ sanctæ Katharina et Margareta aliquando eam fuerunt allocutæ ad fontem quemdam, juxta arborem magnam, communiter appellatam l'abre des fées; de quibus fonte et arbore, fama est divulgata quod Fatales Dominæ ibidem frequentant, et quod plures febricitantes ad dictos fontem et arborem accedunt, causa recuperandæ sanitatis, quamvis siti sint in loco profano. Quas ibi et alibi pluries venerata fuit, et eis reverentiam exhibuit. [...] Militanti vero Ecclesiæ se, sua facta et dicta submittere distulit et recusavit, pluries super hoc requisita et monita, dicens quod impossibile est eidem fœminæ facere contrarium illorum quæ affirmavit in suo processu, se de mandato Dei fecisse, neque de his se referet determinationi aut judicio cujuscumque viventis, sed tantummodo judicio Dei [...]. »",
  "en": "'And first, a certain woman says and affirms that when she was thirteen years old or thereabouts she saw with her bodily eyes Saint Michael comforting her, and sometimes Saint Gabriel, appearing in bodily form. [...] And that the said Saints Catherine and Margaret sometimes spoke to her at a certain spring, beside a great tree commonly called the fairies' tree; of which spring and tree the report goes that the Fates frequent them, and that many people with fever go to the said spring and tree to recover their health, although they stand in a profane place. These she venerated many times there and elsewhere, and did them reverence. [...] But to the Church Militant she has put off and refused to submit herself, her deeds and words, though often required and admonished to do so, saying that it is impossible for her to do the contrary of what she has affirmed in her trial that she did by God's command, and that she will not refer herself in these things to the determination or judgment of anyone living, but only to the judgment of God [...].'",
  "note": "The Twelve Articles, drawn up after the interrogations and sent to the consultors on 5 April 1431, are not her words but a summary of them, in the third person: 'a certain woman says'. Her answers in court had been more careful: compare her words on the Church in the prison sessions (Interr. Prison [1]). Whether they fairly stated her answers was one of the questions of the nullity trial; on 23 May they were read to her in French, with the University's verdict. The cuts give the crowns of the saints, their command to go to a prince and to wear men's clothes, and the promise of paradise."},
 {"pg": "332",
  "titel": "Article V: the dress of a man",
  "orig": "« Item, dicta fœmina dicit et affirmat quod, de mandato Dei et ejus bene placito, assumpsit et portavit, ac continue portat et vestit habitum ad usum viri. Et ulterius dicit quod, ex quo habebat de mandato Dei deferre habitum viri, oportebat eam accipere tunicam brevem, capucium, giponem, braccas et caligas cum aguilletis multis, capillis capitis sui super summitates aurium scissis in rotundum; nihil super corpus suum relinquendo, quod sexum fœmineum approbet aut demonstret, præter ea quæ natura eidem fœminæ contulit ad fœminei sexus distinctionem. Quodque in prædicto habitu, pluries eucharistiam recepit. Nec voluit aut vult habitum muliebrem resumere, pluries super hoc caritative requisita et monita, dicens quod mallet mori quam habitum virilem dimittere, aliquotiens simpliciter dicendo, et aliquando, « nisi esset de mandato Dei. » Et quod, si in habitu viri esset inter eos pro quorum parte alias se armavit, et faceret sicut faciebat ante captionem suam et detentionem, hoc esset unum de maximis bonis quod evenire posset toti regno Franciæ; addendo quod, pro nulla re mundi, faceret juramentum de non portando habitum viri et de non armando se. Et in omnibus præmissis, dicit se bene fecisse et bene facere, obediendo Deo et mandatis ejus. »",
  "en": "'Item, the said woman says and affirms that by God's command and good pleasure she took and wore, and continually wears and dresses in, clothing for a man's use. And further she says that, since she had God's command to wear a man's dress, she had to take a short tunic, a hood, a doublet, breeches and hose with many laces, the hair of her head cut round above the tops of her ears, leaving nothing on her body to prove or show the female sex, except what nature gave the said woman to distinguish the female sex. And that in the said dress she has many times received the Eucharist. Nor would she, or will she, take back a woman's dress, though often charitably required and admonished to do so, saying that she would rather die than leave off a man's dress, sometimes saying this simply and sometimes \"unless it were by God's command\". And that if she were in a man's dress among those for whose side she once armed herself, and did as she did before her capture and detention, it would be one of the greatest goods that could happen to the whole kingdom of France; adding that for nothing in the world would she take an oath not to wear a man's dress and not to arm herself. And in all the above she says she did well and does well, obeying God and his commands.'",
  "note": "The article on which the trial would end. The clothing is described piece by piece, down to the laces that tied the hose to the doublet, which witnesses of the nullity trial said she kept tightly fastened in prison. The Faculty of Theology called it blasphemy and idolatry (Art. University [2]); the abjuration of 24 May would include the promise not to wear it again, and her return to it would make her relapsed."},
 {"pg": "336",
  "titel": "Article XII: not to any man in the world",
  "orig": "« Item, dicta fœmina dicit et confitetur quod, si Ecclesia vellet quod ipsa faceret aliquid contrarium de præcepto quod dicit sibi fuisse factum a Deo, ipsa non faceret illud pro quacumque re; affirmando quod ipsa bene scit quod ea quæ continentur in suo processu, veniunt per præceptum Dei, quodque eidem esset impossibile facere contrarium eorum. Neque de his se vult referre ad determinationem Ecclesiæ militantis, aut quemcumque hominem mundi; sed ad solum Deum Dominum nostrum, cujus præcepta semper faciet, præcipue quoad materiam revelationum, et eorum quæ dicit se fecisse per revelationes. [...] quamvis dictæ fœminæ, per judices et alios ibidem præsentes, sæpius fuerit declaratus articulus fidei, qui est, Unam sanctam Ecclesiam catholicam, eidem exprimendo quod quilibet fidelis viator tenetur obedire, et facta ac dicta sua submittere Ecclesiæ militanti, præcipue in materia fidei et quæ tangit doctrinam sacram et ecclesiasticas sanctiones. »",
  "en": "'Item, the said woman says and confesses that if the Church wished her to do anything contrary to the command she says was given her by God, she would not do it for anything; affirming that she knows well that what is contained in her trial comes by God's command, and that it would be impossible for her to do the contrary. Nor will she refer herself in these matters to the determination of the Church Militant, or of any man in the world, but to God our Lord alone, whose commands she will always do, above all in the matter of her revelations and of what she says she did by revelation. [...] although the article of faith \"One holy catholic Church\" was declared to the said woman many times by the judges and others present, it being explained to her that every faithful Christian in this life is bound to obey, and to submit his deeds and words to the Church Militant, above all in matters of faith and what touches sacred doctrine and the laws of the Church.'",
  "note": "The article that made the case one of heresy rather than of superstition: a refusal to submit to the Church Militant was schism. The cut says that she made these answers 'not relying on her own head' but by the command of her voices. In the prison sessions she had said she would answer the question of submission later, and had asked to be taken before the pope (Interr. Prison [1])."},
]

VERDICT = [
 {"pg": "339",
  "titel": "The doctors at Rouen: 'invented by human means, or from an evil spirit'",
  "orig": "« Dicimus quod, qualitate personæ, dictis, factis suis modisque apparitionum et revelationum, fine, materia omniumque prædictorum circumstantiis ac omnibus in prædictis articulis et processu contentis, diligenter attentis, collatis invicem et pensatis: censendum est prædictas apparitiones et revelationes quas jactat et asserit se habuisse a Deo per angelos et Sanctas, non fuisse a Deo per dictos angelos et Sanctas; imo potius fictiones quasdam humanitus adinventas, aut a maligno spiritu processisse; nec ad hoc credendum et sciendum, signa sufficientia habuisse; in prædictisque articulis esse et contineri mendacia conficta; aliqua non verisimilia, leviter credita ab ea; superstitiosas quoque divinationes; scandalosa et irreligiosa facta; aliqua dicta temeraria, præsumptuosa, plena jactantiis; blasphemiam in Deum et Sanctas; impietatem erga parentes; aliqua non consona præcepto de dilectione proximi; idolatriam aut, ad minus, confictionem mendosam; schismatica de unitate, auctoritate et potestate Ecclesiæ; male sapientia, ac de hæresi vehementer suspecta. »",
  "en": "'We say that, having diligently attended to, compared and weighed the quality of the person, her words and deeds, the manner of the apparitions and revelations, their end and matter, all their circumstances, and everything contained in the said articles and the trial, it is to be judged that the said apparitions and revelations, which she boasts and asserts she had from God through angels and saints, were not from God through those angels and saints; but rather certain fictions invented by human means, or proceeding from an evil spirit; that she had no sufficient signs to believe and know this; that the said articles contain made-up lies; some things not likely, lightly believed by her; superstitious divinations; scandalous and irreligious deeds; some rash and presumptuous words full of boasting; blasphemy against God and the saints; impiety towards her parents; some things not in keeping with the commandment to love one's neighbour; idolatry or at least lying invention; schismatic things concerning the unity, authority and power of the Church; things wrongly thought, and vehemently suspect of heresy.'",
  "note": "The opinion of sixteen doctors and six licentiates and bachelors of theology gathered in the chapel of the archbishop's manor at Rouen on 12 April 1431, under Érard Emengart; Jean Beaupère, Nicolas Midi and Thomas de Courcelles were among them. Nearly all had sat as assessors. The notary who drew up the instrument was Guillaume Manchon, who in 1450–1456 would testify about the trial."},
 {"pg": "414–417",
  "titel": "The Faculty of Theology of Paris",
  "orig": "« Et primo, quoad primum articulum, dicit ipsa Facultas per modum doctrinæ, pensatis fine, modo et materia revelationum, qualitate personæ ac loco cum aliis circumstantiis, quod vel sunt ficta mendacia, seductoria et perniciosa, vel prædictæ apparitiones et revelationes sunt superstitiosæ, a malignis spiritibus et diabolicis, Belial, Satan et Behemmoth, procedentes. » [...] « Item, quoad quintum articulum, quod dicta fœmina est blasphema in Deum et contemptrix Dei in suis sacramentis, legis divinæ et sacræ doctrinæ ac sanctionum ecclesiasticarum prævaricatrix, male sapiens et errans in fide, et se jactans inaniter, et habenda est suspecta de idolatria et exsecratione sui ac vestium suarum, ritum gentilium imitando. » « Item, quoad sextum articulum, quod dicta fœmina est proditrix, dolosa, crudelis et sitibunda effusionis sanguinis humani, seditiosa et ad tyrannidem provocans; blasphematrix Dei in mandatis et revelationibus suis. » [...] « Item, quoad duodecimum articulum, quod dicta fœmina est schismatica, male sentiens de unitate et auctoritate Ecclesiæ, apostatrix; et huc usque pertinaciter errat in fide. »",
  "en": "'And first, as to the first article, the Faculty says by way of doctrine, having weighed the end, manner and matter of the revelations, the quality of the person and the place, with the other circumstances, that either they are made-up lies, seductive and pernicious, or the said apparitions and revelations are superstitious, proceeding from evil and diabolical spirits, Belial, Satan and Behemoth.' [...] 'Item, as to the fifth article, that the said woman is a blasphemer against God and a despiser of God in his sacraments, a transgressor of divine law, sacred doctrine and the laws of the Church, thinking wrongly and erring in the faith, vainly boasting, and to be held suspect of idolatry and of devoting herself and her clothes to evil, imitating the rites of the heathen.' 'Item, as to the sixth article, that the said woman is a traitor, deceitful, cruel and thirsting for the shedding of human blood, seditious and inciting to tyranny; a blasphemer of God in her commands and revelations.' [...] 'Item, as to the twelfth article, that the said woman is schismatic, thinking wrongly of the unity and authority of the Church, an apostate; and up to now errs obstinately in the faith.'",
  "note": "Read before the University assembled at Saint-Bernard in Paris on 14 May 1431, 'the apostolic see, as it is said, being without a shepherd' (Martin V had died on 20 February; Eugenius IV had been elected on 3 March). The faculty submitted its verdict to the pope and a general council, a formula the court would not grant Jeanne. The University of Paris, in English-held Paris, had written to the duke of Burgundy for her delivery to the Church within days of her capture. Sixth article: her letters threatening death to those who would not obey."},
 {"pg": "417–418",
  "titel": "The Faculty of Decrees: 'if she affirms them obstinately'",
  "orig": "« Si dicta fœmina, compos sui, affirmaverit pertinaciter propositiones in duodecim articulis suprascriptis declaratas, et facta contenta in eisdem opere adimpleverit, visitatis diligenter propositionibus supradictis, videtur Facultati decretorum, per modum consilii vel doctrinæ, caritative loquendo: » « Primo, quod dicta fœmina est schismatica, cum schisma sit illicita divisio, per inobedientiam, ab unitate Ecclesiæ facta, et ipsa se separat ab obedientia Ecclesiæ militantis, prout dicit, etc. » « Item, quod ipsa fœmina est erronea in fide; contradicit articulo fidei, contento in symbolo minori, Unam sanctam Ecclesiam catholicam [...]. » « Item, et quod ipsa fœmina est etiam apostatrix, tum quia comam quam sibi Deus dedit ad velamen, malo proposito sibi amputari fecit, tum etiam quia, eodem proposito, relicto habitu muliebri, virorum habitum imitata est. » « Item, et quod ipsa fœmina est mendosa ac divinatrix, cum dicit se missam a Deo, et loqui angelis ac Sanctis, et non ostendit per operationem miraculi vel scripturæ testimonio speciali [...]. »",
  "en": "'If the said woman, being in her right mind, has obstinately affirmed the propositions set out in the twelve articles above, and carried out in deed the acts contained in them, it seems to the Faculty of Decrees, having diligently considered the said propositions, by way of counsel or doctrine, speaking in charity:' 'First, that the said woman is schismatic, since schism is an unlawful division from the unity of the Church made by disobedience, and she separates herself from obedience to the Church Militant, as she says, etc.' 'Item, that the said woman errs in the faith; she contradicts the article of faith contained in the lesser creed, One holy catholic Church [...].' 'Item, that the said woman is also an apostate, both because she had the hair that God gave her for a veil cut off with evil intent, and because, with the same intent, leaving a woman's dress, she imitated the dress of men.' 'Item, that the said woman is a liar and a diviner, since she says she is sent by God and speaks with angels and saints, and does not show it by working a miracle or by a special testimony of scripture [...].'",
  "note": "The canonists made their verdict conditional: if she affirmed the articles 'obstinately' and 'in her right mind'. That condition was the opening the court would use: on 23 May she was admonished, on 24 May at Saint-Ouen she abjured, and when she was found relapsed the condition was fulfilled. The fourth article cites Moses and John the Baptist (the cut): a true messenger shows a miracle or a text."},
]

SECTIONS = [
    {"id": "charges", "zk": "Art. Charges", "titel": "The promoter's charges, 27 March 1431",
     "blurb": "The preamble of the seventy articles of the prosecutor Jean d'Estivet: everything the court might call her, in one sentence.",
     "units": CHARGES},
    {"id": "twelve", "zk": "Art. Twelve", "titel": "The Twelve Articles, 5 April 1431",
     "blurb": "Her answers reduced to twelve propositions about 'a certain woman' and sent to the consultors: the voices and the fairies' tree, the dress of a man, and the refusal to submit to the Church Militant.",
     "units": TWELVE},
    {"id": "university", "zk": "Art. University", "titel": "The verdicts: the doctors of Rouen and the University of Paris",
     "blurb": "The doctors gathered at Rouen on 12 April, and the faculties of theology and decrees of the University of Paris on 14 May 1431: fictions or devils, blasphemy, schism and apostasy, if she persists.",
     "units": VERDICT},
]
