"""Jeanne d'Arc's letters, 1429-1430, from Jules Quicherat, Procès de
condamnation et de réhabilitation de Jeanne d'Arc, vol. V (Paris 1849),
'Lettres, actes et autres pièces détachées', nos. I, X, XV, XX and XXIV.

Internet Archive ProcesDeCondamnationV5 (Google scan); the image number is
taken from the scan's page-number index. The OCR was used to find the places;
every excerpt was read against the page images. Quicherat's text is kept,
with his spelling of the copies he followed; cuts are marked [...].

Jeanne could not write. The letters were dictated, and she said at her trial
that she had dictated them herself (Interr. Public [5]). The letter to the
Hussites survives only in a German version, printed by Quicherat beside his
French; it is carried in German.

English: the site's working translation (CC0).

Each unit: pg (Quicherat V page), titel, orig, en, note, lang."""

LETTERS = [
 {"pg": "96–97", "lang": "fr",
  "titel": "To the English before Orléans (22 March 1429)",
  "orig": "Jhesus Maria. Roy d'Angleterre, et vous duc de Bethfort qui vous dites regens le royaulme de France ; Guillaume de Lapoula, conte de Suffort, Jehan sire de Thalebot, et vous Thomas, sire d'Escalles, qui vous dictes lieutenans dudit de Bethfort, faites rayson au roy du ciel de son sang royal ; rendés à la Pucelle cy envoiée de par Dieu le roy du ciel, les clefs de toutes les bonnes villes que vous avés prises et violées en France. Elle est ayci venue de par Dieu le roy du ciel, pour reclamer le sang royal ; elle est toute preste de faire paix, se vous luy vollés faire rayson par ainssi que France vous mectés sur et paiés de ce que l'avez tenu. Entre vous archiers, compaignons de guerre gentilz, et autres qui estes davant la bonne ville d'Orliens, alés vous an, de par Dieu, en vous païs ; et se ainssi ne le faictes, attendés lez nouvelles de la Pucelle qui vous ira veoir briefment à vostre bien grant domaige. Roy d'Angleterre, se ainssi ne le faites, je suis chief de guerre, et en quelque lieu que je attaindré vous gens en France, je lez en feray aller, veulhent ou non veulhent ; et se ilz ne veullent obéir, je le feré toulx mourir, et se ilz veullient obéir, je lez prandray à mercy. Je suis cy venue de par Dieu, le roy du ciel, corps pour corps pour vous bouter hors de toute France, encontre tous ceulx qui vouldroient porter traïson, malengin ne domaige au royaulme de France. Et n'aiés point en vostre oppinion, que vous ne tenrés mie le royaulme de France de Dieu, le roy du ciel, filz de saincte Marie ; ains le tenra le roy Charles, vray héritier ; quar Dieu, le roy du ciel, le vieult ainssi, et luy est revelé par la Pucelle : lequel entrara à Paris à bonne compaignie. Se vous ne voulés croire lez nouvelles de par Dieu de la Pucelle, en quelque lieu que nous vous trouverons, nous ferrons dedans à horions, et si ferons ung si gros hahaye, que encores ha mil années que en France ne fut fait si grant, se vous ne faictes rayson. Et creés fermement que le roy du ciel trouvera plus de force à la Pucelle que vous ne luy sauriés mener de toulx assaulx, à elle et à ses bonnes gens d'armes ; et adonc verront les quielx auront meilleur droit, de Dieu du ciel ou de vous. [...]",
  "en": "Jesus Maria. King of England, and you, duke of Bedford, who call yourself regent of the kingdom of France; William de la Pole, earl of Suffolk, John lord Talbot, and you, Thomas lord Scales, who call yourselves lieutenants of the said Bedford: give satisfaction to the King of Heaven for his royal blood; give up to the Maid, who is sent here by God the King of Heaven, the keys of all the good towns you have taken and violated in France. She has come here from God the King of Heaven to claim the royal blood; she is quite ready to make peace, if you will give her satisfaction, by leaving France and paying for having held it. And you, archers, gentle companions of war, and others who are before the good town of Orléans, go back to your own country, in God's name; and if you do not, wait for news of the Maid, who will come to see you shortly, to your very great harm. King of England, if you do not do so, I am a chief of war, and wherever I meet your people in France I will make them leave, whether they will or not; and if they will not obey, I will have them all put to death; and if they will obey, I will take them to mercy. I am come here from God, the King of Heaven, body for body, to drive you out of all France, against all who would bring treason, malice or harm to the kingdom of France. And do not hold to your opinion, for you will never hold the kingdom of France from God, the King of Heaven, son of Saint Mary; but King Charles will hold it, the true heir, for God the King of Heaven wills it so, and it is revealed to him by the Maid; and he will enter Paris in good company. If you will not believe the news from God by the Maid, wherever we find you we shall strike into you with blows, and make so great a tumult that there has not been so great a one in France for a thousand years, if you do not give satisfaction. And believe firmly that the King of Heaven will send more strength to the Maid than you can bring against her in all your assaults, to her and her good men-at-arms; and then it will be seen who has the better right, the God of Heaven or you. [...]",
  "note": "Dictated at Poitiers, after the examination by the churchmen, and sent before the march to Orléans. Quicherat prints it from two eighteenth-century transcripts of a lost contemporary copy, which had been folded inside a Latin letter by a writer plainly of her party; he printed it to show that the three phrases Jeanne denied at her trial ('give up to the Maid', 'chief of war', 'body for body') stand in every copy, including those of her own party; the version inserted in the trial is in vol. I, p. 240. He also notes that the clause 'against all who would bring treason...' is found in no other copy. The cut asks Bedford not to bring destruction on himself, says that if he gives satisfaction the French may yet do 'the finest deed ever done for Christendom', and ends: 'Written on the Tuesday of Holy Week. From the Maid.' Many years would pass, but her last sentence would be answered: Paris in 1436, Rouen in 1449."},
 {"pg": "126–127", "lang": "fr",
  "titel": "To the duke of Burgundy, on the day of the coronation (17 July 1429)",
  "orig": "Jhesus Maria. Hault et redoubté prince, duc de Bourgoingne, Jehanne la Pucelle vous requiert de par le Roy du ciel, mon droicturier et souverain seigneur, que le roy de France et vous, faciez bonne paix ferme, qui dure longuement. Pardonnez l'un à l'autre de bon cuer, entièrement, ainsi que doivent faire loyaulx chrestians ; et s'il vous plaist à guerroier, si alez sur les Sarrazins. Prince de Bourgoingne, je vous prie, supplie et requiers tant humblement que requerir vous puis, que ne guerroiez plus ou saint royaume de France, et faictes retraire incontinent et briefment voz gens qui sont en aucunes places et forteresses dudit saint royaume ; et de la part du gentil roy de France, il est prest de faire paix à vous, sauve son honneur, s'il ne tient en vous. Et vous faiz à savoir de par le Roy du ciel, mon droicturier et souverain seigneur, pour vostre bien et pour vostre honneur et sur voz vie, que vous n'y gaignerez point bataille à l'encontre des loyaulx François, et que tous ceulx qui guerroient oudit saint royaume de France, guerroient contre le roy Jhesus, roy du ciel et de tout le monde, mon droicturier et souverain seigneur. [...] Et a trois sepmaines que je vous avoye escript et envoié bonnes lettres par ung hérault, que feussiez au sacre du roy qui, aujourdui dimenche, xvije jour de ce présent mois de juillet, ce fait en la cité de Reims : dont je n'ay eu point de response, ne n'ouy oncques puis nouvelles dudit hérault. A Dieu vous commens et soit garde de vous, s'il lui plaist ; et prie Dieu qu'il y mecte bonne pais. Escript audit lieu de Reims, ledit xvije jour de juillet. Sur l'adresse : Au duc de Bourgoigne.",
  "en": "Jesus Maria. High and dread prince, duke of Burgundy, Jeanne the Maid requires you, on behalf of the King of Heaven, my rightful and sovereign lord, that the king of France and you make a good, firm peace that will last long. Forgive one another wholly with a good heart, as loyal Christians should; and if it pleases you to make war, go against the Saracens. Prince of Burgundy, I pray, beseech and require you as humbly as I can, that you make no more war in the holy kingdom of France, and withdraw at once your people who are in any places and fortresses of the said holy kingdom; and for his part the gentle king of France is ready to make peace with you, saving his honour, if it rests with you. And I let you know, on behalf of the King of Heaven, my rightful and sovereign lord, for your good and your honour and on your lives, that you will win no battle against the loyal French, and that all who make war in the said holy kingdom of France make war against King Jesus, king of heaven and of all the world, my rightful and sovereign lord. [...] And three weeks ago I wrote and sent you good letters by a herald, asking you to be at the coronation of the king, which today, Sunday the seventeenth of this present month of July, is taking place in the city of Reims; to which I have had no answer, nor have I heard any news of the herald since. I commend you to God, may he keep you if it please him; and I pray God to make a good peace. Written in the said place of Reims, the said seventeenth day of July. On the address: To the duke of Burgundy.",
  "note": "The original is in the archives at Lille, once of the Chambre des comptes of Flanders; Quicherat established his text from a facsimile. Written on the day of the coronation, to the prince whose father had been murdered in the king's presence in 1419 and who was the ally of the English. Philip the Good did not answer; ten months later it was his men who took her at Compiègne. He made peace with Charles VII at Arras in 1435. The cut warns that whatever numbers he brings 'they will win nothing there', and that it will be 'great pity of the great battle and of the blood that will be shed'."},
 {"pg": "139–140", "lang": "fr",
  "titel": "To the people of Reims: 'I am not content with these truces' (5 August 1429)",
  "orig": "Mes chiers et bons amis les bons et loyaux François de la cité de Rains, Jehanne la Pucelle vous faict à savoir de ses nouvelles, et vous prie et vous requiert que vous ne faicte nul doubte en la bonne querelle que elle mayne pour le sang royal ; et je vous promet et certiffy que je ne vous abandoneray poinct tant que je vivray. Et est vray que le roy a faict trêves au duc de Bourgoigne quinze jour durant, par ainsi qu'il ly doibt rendre la cité de Paris paisiblement au chieff de quinze jour. Cependant ne vous donnés nule merveille se je ne y entre si brieffvement, combien que des trêves qui ainsi sont faictes je ne soy point contente et ne sçay si je les tendroy ; mais si je les tiens, ce sera seulement pour garder l'honneur du roy ; combien aussy que ilz ne rabuseront point le sang royal, car je tiendray et maintiendray ensemble l'armée du roy pour estre toute preste au chief desdictz quinze jours, s'ils ne font la paix. [...] et me faictes savoir scil y a nuls triteurs qui vous veullent grever, et au plus brief que je pourray, je les en osteray ; et me faictes sçavoir de vos nouvelles. A Dieu vous commande qui soit garde de vous. Escript ce vendredy, cinquiesme jour d'aoust, emprès un logis sur champ ou chemin de Paris. Sur l'adresse : Aux loyaux Francxois habitans en la ville de Rains.",
  "en": "My dear and good friends, the good and loyal French of the city of Reims, Jeanne the Maid sends you her news, and prays and requires you to have no doubt of the good cause she leads for the royal blood; and I promise and assure you that I will not abandon you as long as I live. It is true that the king has made a truce with the duke of Burgundy for fifteen days, on condition that he hand over the city of Paris peacefully at the end of the fifteen days. Meanwhile do not wonder if I do not enter it so soon, although I am not content with the truces thus made and do not know if I will keep them; but if I keep them, it will only be to guard the king's honour; and also they will not deceive the royal blood, for I will keep and maintain the king's army together, to be quite ready at the end of the fifteen days if they do not make peace. [...] and let me know if there are any traitors who wish to harm you, and as soon as I can I will remove them; and send me your news. I commend you to God, may he keep you. Written this Friday, the fifth day of August, near a lodging in the fields on the road to Paris. On the address: To the loyal French living in the town of Reims.",
  "note": "The original was at the town hall of Reims in the early seventeenth century; only a copy of that time survives. Two later letters to Reims, of 16 and 28 March 1430, are not carried here. The fortnight's truce with Burgundy did not give Paris to the king; the attack on Paris on 8 September failed, and she was wounded at the Saint-Honoré gate. The letter shows her at odds with the king's council within three weeks of the coronation. The cut asks them not to be uneasy as long as she lives, and to keep good watch and guard the king's good city."},
 {"pg": "147–148", "lang": "fr",
  "titel": "To the people of Riom: powder and saltpetre (9 November 1429)",
  "orig": "Chers et bons amis, vous savez bien comment la ville de Saint-Pierre le Moustier a esté prinse d'assault ; et, à l'aide de Dieu, ay entencion de faire vuider les autres places qui sont contraires au roy ; mais pour ce que grant despense de pouldres, trait et autres habillemens de guerre a esté faicte devant ladicte ville, et que petitement les seigneurs qui sont en ceste ville et moy en sommes pourveuz pour aler mectre le siége devant La Charité, où nous alons présentement : je vous prie sur tant que vous aymez le bien et honneur du roy et aussi de tous les autres de par deçà, que vueillez incontinant envoyer et aider pour ledit siége, de pouldres, salpestre, souffre, trait, arbelestres fortes et d'autres habillemens de guerre. Et en ce faictes tant que, par faulte desdictes pouldres et autres habillemens de guerre, la chose ne soit longue, et que on ne vous puisse dire en ce estre négligens ou refusans. Chiers et bons amis, Nostre Sire soit garde de vous. Escript à Molins, le neufviesme jour de novembre. Signé : Jehanne. Sur l'adresse : A mes chers et bons amis, les gens d'église, bourgois et habitans de la ville de Rion.",
  "en": "Dear and good friends, you know well how the town of Saint-Pierre-le-Moûtier has been taken by assault; and with God's help I intend to clear the other places that are against the king; but because great expense of powder, arrows and other equipment of war was made before the said town, and the lords who are in this town and I are poorly provided to go and lay siege to La Charité, where we are going now, I pray you, as you love the good and honour of the king and of all the others on this side, to send at once and help for the said siege with powder, saltpetre, sulphur, arrows, strong crossbows and other equipment of war. And do so, that for want of the said powder and other equipment the matter may not be long, and that no one may say you were negligent or unwilling in this. Dear and good friends, our Lord keep you. Written at Moulins, the ninth day of November. Signed: Jehanne. On the address: To my dear and good friends, the churchmen, burgesses and inhabitants of the town of Riom.",
  "note": "The original, found at Riom in 1844, bears her signature; Quicherat, who held it, thought the unsteady letters showed that her hand had been guided, which agrees with her own statement that she could not write. The red wax seal is broken; on its back, he says, one sees the mark of a finger and the remains of a black hair that seems to have been put into the wax. The siege of La Charité failed in December. A letter about saltpetre: the war as it was, not as the trial would describe it."},
 {"pg": "156–159", "lang": "de",
  "titel": "To the Hussites of Bohemia (March 1430)",
  "orig": "Jesus Maria. Schon lange kam es durch das unbestaendige Geruecht, kuerzlich aber neuerdings durch die bestaendige Stimme des Volkes als Gottesstimme zu meinen Ohren zu meiner, des Maedchens Johanna, Kenntnisz, dasz ihr aus Christen, Ketzer dasz ihr blinde Heiden und Sarazenen geworden seyd, dasz ihr den aechten Glauben und alles Erbauliche des Gottesdienstes aufgehoben habt, dafuer aber einem empoerenden Aberglauben froehnet, dasz ihr ihn durch diese Mittel des Schreckens und der Schmach gewaltsam fortzupflanzen erlaubt, heilige Bilder zerstoert, heilige Gebaende in Schutt und Truemmer legt! Seyd ihr denn voellig rasend? Welche sinnlose Wuth ist in euch losgelassen? [...] Ich, das Maedchen Johanna, haette Euch, um wahr von dem Wahren zu reden, laengst mit strafenden Arm heimgesucht, wenn der Krieg mit den Englaendern mich nicht noch immer hier festhielte. Aber hoere ich nicht bald von Euerer Besserung, von Euerer Rueckkehr in den Schoosz der Kirche, so lasse ich vielleicht von den Englaendern, und kehre mich gegen Euch, um den empoerenden Aberglauben mit des Eisens Schaerfe auszutilgen und Euch entweder die Ketzerei oder das Leben zu nehmen. Kehrt ihr jedoch zum vorigen Lichte, kehrt ihr in den Schoosz des katholischen Bekenntnisses zurueck, so sendet Euere Gesandten zu mir. Ich werde ihnen sagen, was Ihr zu thun habt. Verstockt Ihr aber in Euerer Widerspentigkeit, so moege die Grauengestalt des Schadens, den Ihr angerichtet, der Laster, womit Ihr Euch befleckt habt, Euern Muth erschuettern. Erwartet mich mit der staerksten menschlichen und goettlichen Macht um Euch Gleiches mit Gleichem zu vergelten. Gegeben zu Sully, am 3 Maerz.",
  "en": "Jesus Maria. For a long time now, through uncertain rumour, but lately through the constant voice of the people, which is the voice of God, it has come to my ears, to the knowledge of me, Jeanne the Maid, that from Christians you have become heretics, blind heathens and Saracens; that you have abolished the true faith and all that edifies in the service of God, and given yourselves instead to a revolting superstition; that you allow it to be spread by force, by these means of terror and shame; that you destroy holy images and lay holy buildings in rubble and ruin! Are you then wholly mad? What senseless fury has been let loose in you? [...] I, Jeanne the Maid, to speak the truth, would long since have visited you with a punishing arm, if the war with the English did not still hold me here. But if I do not soon hear of your amendment, of your return to the bosom of the Church, I may perhaps leave the English and turn against you, to root out the revolting superstition with the edge of the sword and take from you either your heresy or your life. If, however, you return to the former light, to the bosom of the catholic confession, send your envoys to me. I will tell them what you have to do. But if you persist in your stubbornness, may the horrible shape of the harm you have done, and of the vices with which you have stained yourselves, shake your courage. Expect me with the strongest human and divine power, to repay you like for like. Given at Sully, on 3 March.",
  "note": "Known to Quicherat only in a German translation, published by Hormayr in 1834 without saying where it came from, of an original he took to be Latin; he printed it with his own French version, judged it authentic, but 'composed by a clerk' and not comparable with her other letters. He refers to the testimony of the Dominican Johannes Nider on it (vol. IV, p. 503). The first noun is misprinted 'Gernecht' in Quicherat. It is now usually attributed to her confessor, the Augustinian Jean Pasquerel, and a Latin text found since is dated 23 March; this site's timeline follows that date. The cut accuses them of persecuting the faith that God sealed 'by thousands of miracles', and warns that God lets their impiety grow only to cast them into the abyss. On the Hussite side of the same years, see the companion sites The Hussite Beginning and The Hussite Field Armies. The letter was never acted on; two months later she was a prisoner. In the series that this site belongs to, it is the one text in which the two subjects meet."},
]

SECTIONS = [
    {"id": "letters", "zk": "Letters", "titel": "Jeanne's letters, 1429–1430",
     "blurb": "Five letters in her name: the summons to the English before Orléans, the plea for peace to the duke of Burgundy on the coronation day, her discontent with the truces to the people of Reims, a request for powder to Riom with her signature, and the threatening letter to the Hussites of Bohemia.",
     "units": LETTERS},
]
