"""The sentence of nullity, Rouen, 7 July 1456, from Jules Quicherat, Procès
de condamnation et de réhabilitation de Jeanne d'Arc, vol. III (Paris
1845), pp. 355-362.

Internet Archive procsdecondam03joanuoft; page P is image n(P+13). The OCR
was used to find the places; every excerpt was read against the page images.
Cuts are marked [...].

English: the site's working translation (CC0).

Each unit: pg (Quicherat III page), titel, orig, en, note, lang."""

NULLITY = [
 {"pg": "355", "lang": "la",
  "titel": "The judges and the parties",
  "orig": "[...] Hac autem auctoritate apostolica fungentes in hac parte, nos Johannes, Remensis, Guillelmus, Parisiensis, Ricardus, Constantiensis, Dei gratia archiepiscopus et episcopi, ac Johannes Brehal, de ordine Fratrum Prædicatorum, sacræ theologiæ professor, hæreticæ pravitatis in regno Franciæ alter Inquisitor ; judices a sanctissimo domino nostro Papa moderno specialiter delegati ; « Viso processu coram nobis solemniter agitato, in vim suscepti per nos reverenter mandati apostolici nobis directi, pro parte honestæ viduæ Ysabellis d'Arc, olim matris, ac Petri et Johannis dictorum d'Arc, fratrum germanorum, naturalium et legitimorum bonæ memoriæ Johannæ d'Arc, vulgariter dictæ la Pucelle, defunctæ, suorumque parentum nominibus, actorum, contra et adversus subinquisitorem hæreticæ pravitatis in diœcesi Belvacensi constitutum, contra promotorem negotiorum criminalium episcopalis curiæ Belvacensis, nec non contra reverendum in Christo patrem, dominum Guillelmum de Hellanda, episcopum Belvacensem, cæterosque universos [...]",
  "en": "[...] Exercising in this matter that apostolic authority, we, Jean of Reims, Guillaume of Paris, Richard of Coutances, by the grace of God archbishop and bishops, and Jean Bréhal, of the order of Preachers, professor of sacred theology, one of the two inquisitors of heretical depravity in the kingdom of France, judges specially delegated by our most holy lord the present pope; having seen the trial solemnly conducted before us, by virtue of the apostolic mandate addressed to us and reverently received, at the suit of the honest widow Isabelle d'Arc, mother, and of Pierre and Jean d'Arc, full brothers, natural and legitimate, of Jeanne d'Arc of good memory, commonly called the Maid, deceased, in their own names and those of their kin, plaintiffs, against the sub-inquisitor of heretical depravity appointed in the diocese of Beauvais, against the promoter of criminal causes of the episcopal court of Beauvais, and also against the reverend father in Christ, master Guillaume de Hellande, bishop of Beauvais, and all others [...]",
  "note": "Jean Jouvenel des Ursins, archbishop of Reims; Guillaume Chartier, bishop of Paris; Richard Olivier, bishop of Coutances; and the inquisitor Jean Bréhal, under a mandate of Pope Calixtus III (1455). The case was brought as a suit by her mother and brothers against the successors of the court of 1431: Cauchon had died in 1442, and the sitting bishop of Beauvais, the promoter and the sub-inquisitor of his diocese were named as defendants. They did not appear and were declared in default; no one defended the first trial."},
 {"pg": "358–359", "lang": "la",
  "titel": "'More worthy of admiration than of condemnation'",
  "orig": "« Ut de Dei vultu nostrum præsens prodeat judicium, qui spirituum ponderator est, et solus revelationum suarum perfectus est cognitor et judicator verissimus ; qui ubi vult spirat, et quandoque infirma eligit, ut fortia quæque confundat, non deserens sperantes in se, sed adjutor eorum in opportunitatibus et tribulatione ; habita matura deliberatione, tam circa præparatoria quam circa decisionem causæ, cum peritis pariter et probatis ac timoratis viris ; visisque solemnibus eorum determinationibus, tam in tractatibus, magna cum revolutione librorum editis, et compositionibus multorum ; visisque opinionibus, verbo pariter atque scripto, tam super forma quam super materia præfati processus, traditis atque datis, quibus facta dictæ defunctæ magis admiratione quam condemnatione digna existimant ; reprobatorium et determinatum contra eam datum judicium, et formæ et materiæ ratione, plurimum admirantes ; et difficillimum dicentes de talibus determinatum præbere judicium, beato Paulo de suis propriis revelationibus dicente, an eas in corpore vel in spiritu habuerit, se nescire, et Deo super hoc se referre :",
  "en": "'That our present judgement may come forth from the face of God, who weighs the spirits, and who alone is the perfect knower and most true judge of his revelations; who breathes where he will, and sometimes chooses the weak to confound the strong, not forsaking those who hope in him, but their helper in need and in trouble; after mature deliberation, both on the preparation and on the decision of the cause, with men skilled, tried and God-fearing; having seen their solemn determinations, set out in treatises with great turning over of books, and in the writings of many; having seen the opinions, given by word and in writing, on both the form and the matter of the said trial, by which they judge the deeds of the deceased more worthy of admiration than of condemnation, wondering greatly at the judgement of reprobation pronounced against her, by reason both of form and of matter, and saying that it is most difficult to give a determined judgement on such things, since the blessed Paul says of his own revelations that he does not know whether he had them in the body or in the spirit, and refers himself to God in this:'",
  "note": "The heart of the sentence and its limit. The court of 1456 does not say that her voices came from God; it says that no court could know, and that the court of 1431 had presumed to. 'More worthy of admiration than of condemnation' is the opinion of the consulted doctors, which the judges cite rather than adopt. Quicherat notes a manuscript variant, 'detestatum' for 'determinatum'. She was canonized only in 1920."},
 {"pg": "359–360", "lang": "la",
  "titel": "The Twelve Articles to be torn up",
  "orig": "« In primis dicimus atque, justitia exigente, decernimus articulos ipsos incipientes Quædam fœmina in processu prætenso et instrumento prætensarum sententiarum contra dictam defunctam latarum descriptos, fore, fuisse et esse corrupte, dolose, calumniose, fraudulenter et malitiose ex ipsis prætensis processu et confessione dictæ defunctæ extractos ; tacita veritate et expressa falsitate in pluribus punctis substantialibus, et ex quibus deliberantium et judicantium animus poterat in aliam deliberationem pertrahi ; plurimasque circumstantias aggravantes, in processu et confessione præfatis non contentas, indebite adjicientes, et nonnullas circumstantias relevantes et justificantes in pluribus subticendo, formamque verborum, quæ substantiam immutat, alterando. Quapropter ipsos articulos, tanquam falsos, calumniose, dolose extractos, et a confessione eadem difformes, cassamus, irritamus et adnullamus ; ipsosque, quos a dicto processu extrahi fecimus, hic judicialiter decernimus lacerandos.",
  "en": "'First, we say and, as justice requires, decree that the articles beginning \"A certain woman\", written in the pretended trial and in the instrument of the pretended sentences pronounced against the deceased, were, are and shall be corruptly, deceitfully, slanderously, fraudulently and maliciously extracted from the said pretended trial and from the confession of the deceased: the truth kept silent and falsehood stated on several points of substance, by which the minds of those deliberating and judging could be drawn to another decision; many aggravating circumstances not contained in the trial and confession unduly added, and a number of relieving and justifying circumstances passed over in many places, and the form of the words, which changes the substance, altered. Wherefore we quash, annul and make void these articles, as false, slanderously and deceitfully extracted, and not conforming to the confession; and we decree that they, which we have had taken out of the said trial, be here judicially torn up.'",
  "note": "The Twelve Articles (Art. Twelve [1]–[3]) were the document on which the University of Paris and the consultors had judged her without hearing her. The sentence orders a copy torn up in court. The compare page sets her own answer on the Church beside the twelfth article."},
 {"pg": "360–361", "lang": "la",
  "titel": "'Null, invalid, void and empty'",
  "orig": "« Attentisque, circa dicti processus materiam, quadam abjuratione prætensa, falsa, subdola, ac per vim et metum, præsentiam tortoris et comminatam ignis cremationem, extorta, et per dictam defunctam minime prævisa et intellecta ; [...] « Cæterisque omnibus et singulis diligenter attentis quæ in hac parte attendenda et videnda erant ; pro tribunali sedentes, solum Deum præ oculis habentes, per hanc nostram diffinitivam sententiam, quam pro tribunali sedentes ferimus in his scriptis, « Dicimus, pronuntiamus, decernimus et declaramus dictos processus et sententias dolum, calumniam, iniquitatem, repugnantiam, jurisque et facti errorem continentes manifestum, cum abjuratione præfata, exsecutionibus et omnibus inde secutis, fuisse, fore et esse nullos et nullas, invalidos et invalidas, irritas et inanes. « Et nihilominus, quantum opus est, ratione jubente, ipsos et ipsas cassamus, irritamus et adnullamus, ac viribus omnino vacuamus ; dictamque Johannam, ac ipsos actores et parentes ejusdem, nullam notam infamiæ seu maculam, occasione præmissorum, contraxisse seu incurrisse, immunemque a præmissis et expurgatam fore et esse, declarantes, et, in quantum opus est, penitus expurgantes ;",
  "en": "'Having regard, as to the matter of the said trial, to a certain pretended abjuration, false, deceitful, and extorted by force and fear, in the presence of the executioner and under threat of burning, and neither foreseen nor understood by the deceased; [...] and having diligently considered each and every other thing that was to be considered and seen in this matter; sitting as a tribunal, having God alone before our eyes, by this our definitive sentence, which sitting as a tribunal we give in writing, we say, pronounce, decree and declare that the said trials and sentences, containing deceit, slander, iniquity, contradiction, and manifest error of law and of fact, together with the said abjuration, the executions and all that followed from them, were, are and shall be null, invalid, void and empty. And nevertheless, so far as is needed, as reason commands, we quash, annul and make them void, and deprive them wholly of force; and we declare that the said Jeanne, and the plaintiffs and her kin, contracted and incurred no mark or stain of infamy by reason of the foregoing, and are and shall be free and cleansed of it, and so far as is needed we wholly cleanse them.'",
  "note": "The cut cites the doctors who held that the crimes in the sentences could not be drawn from the trial. 'Extorted by force and fear, in the presence of the executioner and under threat of burning': the court adopts what Massieu had told it (Wit. Rouen [2]). The wording repeats the declaration, 'null, invalid, void and empty', and then annuls 'so far as is needed', in case anything had been valid."},
 {"pg": "361–362", "lang": "la",
  "titel": "A procession, a sermon, and a cross in the Old Market",
  "orig": "« Ordinantes nostræ hujusmodi sententiæ exsecutionem seu solemnem intimationem in hac civitate protinus fieri, in locis duobus : altero videlicet in promptu, in platea Sancti Audoeni, generali processione præcedente, et in sermone generali ; et in alio, die crastina, in Veteri Foro, in loco scilicet in quo dicta Johanna crudeli et horrenda crematione suffocata est, cum solemni ibidem prædicatione et affixione crucis honestæ ad memoriam perpetuam, ac ejusdem et aliorum defunctorum exorandas salutes ; ulteriorem dictæ nostræ sententiæ exsecutionem, intimationem, et, pro futura memoria, notabilem significationem in civitatibus et hujus regni locis insignibus, prout viderimus expedire, et si quæ alia supersint peragenda, nostræ dispositioni et ex causa reservantes. « Lata, lecta et promulgata fuit hæc præsens sententia per dominos Judices, præsentibus reverendo in Christo patre, domino episcopo Dimitriensi ; Hectore de Coquerel, Nicolao du Boys, Alano Olivier, Johanne du Bec, Johanne de Gouys, Guillelmo Roussel, Laurentio Surreau, canonicis ; Martino Ladvenu, Johanne Roussel, Thoma de Fanoullières. De quibus omnibus magister Simon Chapitault, promotor, Johannes d'Arc, et Prevosteau, pro aliis, petierunt instrumentum, etc. « Acta fuerunt hæc in palatio archiepiscopali, anno Domini MCCCCLVI, die VII. mensis julii. »",
  "en": "'Ordering the execution or solemn publication of this our sentence to be made forthwith in this city in two places: the one at once, in the square of Saint-Ouen, after a general procession, and in a public sermon; the other on the following day in the Old Market, that is, in the place where the said Jeanne was put to death by cruel and horrible burning, with a solemn sermon there and the setting up of a fitting cross for perpetual memory, and to pray for the salvation of her soul and of the other dead; reserving to our disposition, for cause, the further execution and publication of our sentence, and its notable announcement for future memory in the cities and notable places of this kingdom, as we shall see fit, and whatever else remains to be done.' 'This present sentence was given, read and promulgated by the lord judges in the presence of the reverend father in Christ the bishop of Démétriade; Hector de Coquerel, Nicolas du Bois, Alain Olivier, Jean du Bec, Jean de Gouys, Guillaume Roussel, Laurent Surreau, canons; Martin Ladvenu, Jean Roussel, Thomas de Fanouillères. Of all which master Simon Chapitault, promoter, Jean d'Arc, and Prévosteau for the others, asked for a public instrument, etc. Done in the archbishop's palace, in the year of the Lord 1456, on the seventh day of July.'",
  "note": "The sentence was published where the first one had been: at Saint-Ouen, where she had abjured, and in the Old Market, where she had died. Among those present was Martin Ladvenu, her confessor (End Ladvenu [1]–[4]); her brother Jean asked for the instrument. 'Crudeli et horrenda crematione suffocata est' is the sentence's own phrase and the only description of her death that this site carries. The sentence did not bring her back; the thesis of this apparatus stands as it began: the court of 1431 won its case, England lost France, and twenty-five years later a second court declared the first null."},
]

SECTIONS = [
    {"id": "nullity", "zk": "Null.", "titel": "The sentence of nullity (7 July 1456)",
     "blurb": "The judges and the parties, the refusal to judge her revelations, the Twelve Articles torn up, the declaration that the trial, the abjuration and the sentences were 'null, invalid, void and empty', and the order for a procession, a sermon and a cross in the Old Market.",
     "units": NULLITY},
]
