"""The Journal du siège d'Orléans, from Jules Quicherat, Procès de
condamnation et de réhabilitation de Jeanne d'Arc, vol. IV (Paris 1847),
pp. 94-212 ('Journal du siège d'Orléans et du voyage de Reims').

Internet Archive procsdecondam04joanuoft. The image offset is not constant:
page 141 is image n156, pages 151-164 are n(P+17); the scan's page-number
index is wrong around p. 140. The OCR was used to find the places; every
excerpt was read against the page images. Quicherat's text is kept; cuts
are marked [...].

Quicherat's introduction (pp. 94-95): the Journal was put in its present
form about 1467, when the town paid the clerk Pierre Soudan to write 'the
manner of the siege' on parchment. It calls the Bastard of Orléans count
of Dunois (a title of 1439), uses the chronicles of Berry and Jean
Chartier (published after 1461), and the nullity trial; but the daily
entries are 'evidently copied from a register kept as events happened'.
It is the city's book, not an eyewitness diary in the form we have it.

English: the site's working translation (CC0).

Each unit: pg (Quicherat IV page), titel, orig, en, note, lang."""

ARRIVAL = [
 {"pg": "140–141", "lang": "fr",
  "titel": "The letter received (March 1429)",
  "orig": "Quant les seigneurs et cappitaines angloys eurent leues et entendus les lettres, ilz furent courrouchez à merveilles, et en despit de la Pucelle, disans d'elle moult de villaines parolles, par espécial l'appellant ribaulde, vachiere, la menaschant de la faire brusler, retindrent le hérault porteur des lettres, tenans à mocquerie tout ce que elle leur avoit escript.",
  "en": "When the English lords and captains had read and understood the letters, they were wonderfully angry, and in contempt of the Maid said many vile words of her, in particular calling her whore and cowgirl, and threatening to have her burned; they kept back the herald who carried the letters, and held all she had written to them in mockery.",
  "note": "The Journal copies the letter to the English just before this, in its own version (compare Letters [1]), dated 'the Tuesday in Holy Week'. 'Ribaulde' and 'vachiere' will come back twice before the Tourelles, and the threat of burning was carried out at Rouen two years later; the chronicler of 1467 knew that when he wrote it down."},
 {"pg": "152–153", "lang": "fr",
  "titel": "Into the city by torchlight (29 April 1429)",
  "orig": "[...] car ainsi comme à huyct heures au soir, malgré tous les Angloys qui oncques n'y mirent empeschement aucun, elle y entra armée de toutes pièces, montée sur ung cheval blanc ; et faisoit porter devant elle son estandart, qui estoit pareillement blanc, ouquel avoit deux anges tenans chacun une fleur de liz en leur main ; et ou panon estoit paincte comme une Annonciacion (c'est l'image de Nostre-Dame ayant devant elle ung ange luy présentant ung liz). Elle ainsi entrant dedans Orléans, avoit à son cousté senestre le bastart d'Orléans, armé et monté moult richement. [...] D'autre part, la vindrent recevoir les autres gens de guerre, bourgoys et bourgoyses d'Orléans, portans grant nombre de torches, et faisans autel joye comme se ilz veissent Dieu descendre entre eulx, et non sans cause, car ilz avoient plusieurs ennuys, travaux et peines, et qui pis est grant doubte de non estre secouruz, et perdre tous corps et biens. Mais ilz se sentoyent jà tous reconfortez, et comme desassiégez, par la vertu divine qu'on leur avoit dit estre en ceste simple Pucelle, qu'ilz regardoient moult affectueusement, tant hommes, femmes, que petits enfans. Et y avoit moult merveilleuse presse à toucher à elle, ou au cheval sur quoy elle estoit, tellement que l'un de ceulx qui portoient les torches s'approucha tant de son estandart que le feu se print au panon. Pourquoy elle frappa son cheval des esperons, et le tourna autant gentement jusques au panon, dont elle en estangnit le feu, comme se elle eust longuement suyvy les guerres : ce que les gens d'armes tindrent à grans merveilles, et les bourgois de Orléans aussi ; lesquelz l'accompaignèrent au long de leur ville et cité, faisans moult grant chiere, et par très grant honneur la conduisirent tous jusques auprez de la porte Regnart, en l'ostel de Jacquet Boucher, pour lors thrésorier du duc d'Orléans, où elle fut receue à très grant joye, avecques ses deux frères, et les deux gentilzhommes et leur varlet, qui estoient venuz avecques eulx du pays de Barroys.",
  "en": "[...] for at about eight in the evening, in spite of all the English, who never put any hindrance in the way, she entered, armed at all points, mounted on a white horse; and she had her standard carried before her, which was likewise white, with two angels each holding a fleur-de-lis in their hand; and on the pennon was painted as it were an Annunciation (that is, the image of Our Lady with an angel before her presenting her a lily). As she entered Orléans in this way, she had at her left side the Bastard of Orléans, armed and mounted very richly. [...] On the other side the other men of war, burgesses and burgesses' wives of Orléans came to receive her, carrying a great number of torches, and making such joy as if they saw God come down among them; and not without cause, for they had suffered many troubles, labours and pains, and what was worse, great fear of not being relieved and of losing all, bodies and goods. But they felt themselves already all comforted, and as if the siege were lifted, by the divine virtue they had been told was in this simple Maid, whom they looked on very lovingly, men, women and little children alike. And there was a wonderful press to touch her, or the horse she was on, so that one of those carrying the torches came so near her standard that the pennon caught fire. Whereupon she struck her horse with the spurs and turned it so neatly up to the pennon that she put out the fire, as if she had long followed the wars; which the men-at-arms held a great marvel, and the burgesses of Orléans too. They accompanied her the length of their town and city, making very good cheer, and with very great honour all led her to near the Renard gate, to the house of Jacquet Boucher, then treasurer of the duke of Orléans, where she was received with very great joy, with her two brothers, and the two gentlemen and their servant who had come with them from the Barrois.",
  "note": "Thursday 29 April 1429. She had come from Blois by the Sologne with a supply convoy; the captains kept her out of the city until dark 'to avoid the tumult of the people'. The opening cut tells how the Bastard and the captains met her at Chécy and agreed she should enter only at night; the second, that nobles, captains and burgesses rode behind her. The standard described here is the one she was questioned about at Rouen (Interr. Prison [3])."},
 {"pg": "154–155", "lang": "fr",
  "titel": "'Go back and keep the cows' (30 April 1429)",
  "orig": "La nuyt venue, envoya la Pucelle deux héraulx devers les Angloys de l'ost, et leur manda qu'ilz luy renvoyassent le hérault par lequel elle leur avoit envoyé ses lettres de Bloys. Et pareillement leur manda le bastart d'Orléans que s'ilz ne le renvoyaient, qu'il feroit mourir de male mort tous les Angloys qui estoient prisonniers dedans Orléans, et ceulx aussi qui par aucuns seigneurs d'Angleterre y avoient esté envoyez pour traicter de la rançon des autres. Pour quoy les chefz de l'ost renvoyèrent tous les héraulx et messagiers de la Pucelle, luy mandans par eulx qu'ilz la brusleroient et feroient ardoir, et que elle n'estoit qu'une ribaulde, et comme telle s'en retournast garder les vaches. Dont elle fut fort yrée ; et à ceste occasion, quant vint sur le soir, elle s'en ala au boulevert de la Belle Croix, sur le pont, et de là parla à Glacidas et autres Anglois estans ès Tournelles, et leur dist qu'ils se rendissent de par Dieu, leurs vies sauves seullement. Mais Glacidas et ceulx de sa rote respondirent villainement, l'injuriant et appelant vachère, comme devant, crians moult haut qu'ilz la feroient ardoir, s'ilz la povoient tenir. De quoy elle fut aucunement yrée, et leur respondit qu'ilz mentoyent ; et ce dit, s'en retira dedans la cyté.",
  "en": "When night came, the Maid sent two heralds to the English of the host and bade them send back the herald by whom she had sent them her letters from Blois. And the Bastard of Orléans likewise sent them word that if they did not send him back, he would have all the English who were prisoners in Orléans put to an evil death, and those too who had been sent there by certain lords of England to treat for the ransom of the others. Whereupon the chiefs of the host sent back all the Maid's heralds and messengers, sending her word by them that they would burn her and have her put to the fire, that she was nothing but a whore, and as such should go back to keeping the cows. At this she was very angry; and on that account, towards evening, she went to the bulwark of the Belle-Croix on the bridge, and from there spoke to Glasdale and the other English in the Tourelles, and told them to surrender in God's name, their lives only saved. But Glasdale and those of his company answered vilely, insulting her and calling her cowgirl as before, and crying very loudly that they would have her burned if they could lay hands on her. At which she was somewhat angry, and answered them that they lied; and having said this, she withdrew into the city.",
  "note": "Saturday 30 April. The herald was returned only when the Bastard threatened to kill the prisoners and even the English envoys who had come under safe-conduct to negotiate ransoms; the Journal records the threat without comment. 'Glacidas' is William Glasdale, captain of the Tourelles. Her offer is 'their lives only saved': nothing else."},
]

TOURELLES = [
 {"pg": "159–161", "lang": "fr",
  "titel": "The arrow, and 'En nom de Dieu' (7 May 1429)",
  "orig": "Le jour d'après au plus matin, qui fut samedy, sixiesme jour de may, assaillirent les Françoys les Tournelles et les boulevers et taudis que les Angloys y avoient faiz pour les fortiffier. Et y eut moult merveilleux assault, durant lequel y furent faictz plusieurs beaux faiz d'armes, tant en assaillant que en deffendant, parce que Angloys y estoient grant nombre fort combatans, et garnis habondamment de toutes choses deffensables. [...] Et entre les autres y fut blecée la Pucelle et frappée d'un traict entre l'espaule et la gorge, si avant qu'il passoit oultre : dont tous les assaillans furent moult dolens et courrouchez, et par espécial le bastart d'Orléans, et autres cappitaines qui vindrent devers elle, et luy dirent qu'il valloit mieulx laisser l'assault jusques au lendemain ; mais elle les reconforta par moult belles et hardies paroles, les exhortans d'entretenir leur hardiesse. Lesquelz ne la voulans croire délaissèrent l'assault, et se tirèrent arrière, voulans faire rapporter leur artillerie jusques au lendemain. Dont elle fut très dolente, et leur dist : « En nom de Dieu vous entrerez bien brief dedans, n'ayez doubte, et n'auront les Angloys plus de force sur vous. Pour quoy repousez vous ung peu, beuvez et mengez. » Ce qu'ilz feirent, car à merveilles luy obéissoyent. Et quant ilz eurent beu, elle leur dist : « Retournez de par Dieu à l'assault de rechief, car sans nulle faulte les Anglois n'auront plus de force de eulx deffendre, et seront prinses leurs Tournelles et leurs boulevers. » Et ce dit, laissa son estandart, et s'en ala sur son cheval à ung lieu destourné faire oraison à Nostre Seigneur ; et dist à ung gentilhomme estant là près : « Donnez vous garde, quant la queue de mon estandart sera ou touchera contre le boulevert. » Lequel luy dist ung peu aprez : « Jehanne, la queue y touche ! » Et lors elle luy respondit : « Tout est vostre, et y entrez ! » Laquelle parolle fut toust après congneue prophécie [...].",
  "en": "The next day, very early, which was Saturday the sixth day of May, the French assaulted the Tourelles and the bulwarks and sheds the English had made there to fortify them. And there was a very wonderful assault, in which many fine feats of arms were done, both in attacking and in defending, because the English there were a great number of strong fighters, abundantly furnished with everything for defence. [...] And among others the Maid was wounded there, struck by an arrow between the shoulder and the throat, so deep that it went through; at which all the assailants were very grieved and angry, and especially the Bastard of Orléans and other captains, who came to her and told her it would be better to leave the assault until the next day. But she comforted them with very fine and bold words, urging them to keep up their courage. They, not willing to believe her, gave up the assault and drew back, meaning to have their artillery brought back the next day. At which she was very grieved, and said to them: 'In God's name you will be inside very soon, have no doubt, and the English will have no more strength against you. So rest a little, drink and eat.' Which they did, for they obeyed her wonderfully. And when they had drunk, she said to them: 'Go back to the assault again, in God's name, for without any fail the English will have no more strength to defend themselves, and their Tourelles and their bulwarks will be taken.' And having said this, she left her standard and went on her horse to a place apart to pray to Our Lord; and she said to a gentleman standing near: 'Watch when the tail of my standard is at, or touches, the bulwark.' A little after he said to her: 'Jeanne, the tail touches it!' And then she answered him: 'All is yours, go in!' Which word was soon after known for a prophecy [...].",
  "note": "Quicherat corrects the date in a footnote: read 'seventh'. The Journal is a day behind for these days; the Tourelles were taken on Saturday 7 May, and the English left on Sunday 8 May. The first cut describes the English throwing the assailants down from the walls 'with cannon and other shot, axes, lances, guisarmes, leaden mallets and even with their own hands'. 'En nom de Dieu' is the formula that gives the companion game its title; at her trial she said she had known beforehand that she would be wounded there (not carried here)."},
 {"pg": "161–163", "lang": "fr",
  "titel": "The bridge gives way",
  "orig": "[...] Lesquelz passez oultre se bouttèrent avecques leurs autres compaignons en l'assault qui dura peu deppuis ; car si toust que ilz eurent recommencé, les Angloys perdirent toute force de pouvoir plus résister, et s'en cuidèrent entrer du boulevert dedans les Tournelles : combien que peu d'eulx se peurent sauver, car quatre ou cinq cens combatans qu'ilz estoient furent tous tuez ou noyez, exceptez aucun peu qu'on retint prisonniers, et non pas grans seigneurs, obstant que Glacidas, qui estoit cappitaine et moult renommé en faiz d'armes, le seigneur de Moulins, le seigneur de Pommiers, le bailli de Mente, et plusieurs autres chevaliers banneretz et nobles d'Angleterre, furent noyez, parce qu'en eulx cuidans sauver, le pont fondit soubz eulz : qui fut grant esbahissement de la force des Angloys, et grant dommaige des vaillans Françoys, qui pour leur rançon eussent peu avoir grant finance. Toutesfois feirent ilz grant joye, et louèrent Nostre Seigneur de celle belle victoire qu'il leur avoit donnée [...].",
  "en": "[...] Having crossed over, they threw themselves with their other companions into the assault, which lasted only a little after that; for as soon as they had begun again, the English lost all strength to resist any longer, and thought to get from the bulwark into the Tourelles; yet few of them could save themselves, for the four or five hundred fighting men they were were all killed or drowned, except a few who were kept prisoner, and those not great lords; for Glasdale, who was captain and very renowned in feats of arms, the lord of Moulins, the lord of Pommiers, the bailli of Mantes and several other knights banneret and nobles of England were drowned, because as they thought to save themselves the bridge gave way under them: which was a great dismay to the strength of the English, and a great loss to the valiant French, who could have had great sums for their ransom. Nevertheless they made great joy, and praised Our Lord for the fine victory he had given them [...].",
  "note": "The first cut tells how men from the city crossed the broken arches on a gutter lengthened with a piece of wood, the first of them a knight of Rhodes, Nicole de Giresme, 'more a miracle of Our Lord than anything else'. Quicherat's footnote corrects the Journal: the fall of the bridge was not an accident. The town accounts of 1429 show that it was burned on purpose with a fire-boat moored under it, and record payments for the boat, for its irons, and for resin and grease 'to grease the rags to set fire to the Tourelles'. The chronicler regrets the lost ransoms. The second cut credits the victory to Saint Aignan and Saint Euverte, patrons of Orléans, and records the Te Deum."},
 {"pg": "163–164", "lang": "fr",
  "titel": "Sunday: the English go (8 May 1429)",
  "orig": "Ainçois le lendemain matin, jour de dimenche et septiesme jour de may, celluy mesme an mil quatre cens vingt-neuf, désemparèrent leurs bastilles, et si feirent les Angloys de Sainct-Pouair et d'ailleurs, et levans leur siége se mirent en bataille. Pour quoy la Pucelle, les mareschaulx de Saincte-Sevère et de Rays, [...] La Hire, Alain Giron, Jamet du Tilloy, et plusieurs autres vaillans gens de guerre et citoyens saillirent hors d'Orléans en grant puissance, et se mirent et rangèrent devant eulx en bataille ordonnée. Et en tel point furent très prez l'un de l'autre, l'espace d'une heure entière sans eulx toucher. Ce que les Françoys souffryrent très envis, obtempérans au vouloir de la Pucelle, qui leur commanda et deffendit dès le commancement que, pour l'amour et honneur du sainct dimenche, ne commanchassent point la bataille n'assaillissent les Angloys ; mais se les Angloys les assailloyent, qu'ilz se deffendissent fort et hardiement, et qu'ilz n'eussent nulle paour, et qu'ilz seroient les maistres. L'eure passée, se mirent les Angloys à chemin, et s'en alèrent bien rengez et ordonnez dedans Meung sur Loire, et levèrent et laissèrent totallement le siége, qu'ilz avoient tenu devant Orléans deppuis le douziesme jour d'octobre mil quatre cens vingt huyt jusques à cestui jour. Toutesfoiz ne s'en alèrent ilz ne n'emportèrent sauvement toutes leurs bagues, car aucuns de la garnison de la cité les poursuyvirent et se frappèrent sur la queue de leur armée par divers assaulx, tellement qu'ilz gaignèrent sur eulx grosses bombardes et canons, arcs, arbalestres et autre artillerie.",
  "en": "Rather, the next morning, Sunday the seventh day of May of the same year fourteen hundred and twenty-nine, they abandoned their bastilles, and so did the English of Saint-Pouair and elsewhere, and raising their siege drew up in battle order. Whereupon the Maid, the marshals of Sainte-Sévère and of Rais, [...] La Hire, Alain Giron, Jamet du Tilloy and many other valiant men of war and citizens sallied out of Orléans in great strength and drew up before them in ordered battle. And in this way they were very close to each other for the space of a whole hour without touching. The French bore this very unwillingly, obeying the will of the Maid, who commanded and forbade them from the beginning, for the love and honour of the holy Sunday, to begin the battle or attack the English; but if the English attacked them, they were to defend themselves strongly and boldly and have no fear, and they would be the masters. When the hour had passed, the English set off and went in good order to Meung-sur-Loire, and raised and wholly abandoned the siege they had held before Orléans from the twelfth day of October fourteen hundred and twenty-eight until that day. Yet they did not go away nor carry off all their baggage safely, for some of the garrison of the city pursued them and fell on the rear of their army in several attacks, so that they took from them great bombards and cannon, bows, crossbows and other artillery.",
  "note": "Quicherat's footnote: read 'eighth'. The cut names the other captains. The day is still kept at Orléans as the Fêtes johanniques. The siege had lasted from 12 October 1428, almost seven months; the Maid had been in the city since the evening of 29 April. After the cut the Journal tells of an English Augustinian, Talbot's confessor, forced by his prisoner, a French man-at-arms in leg-irons, to carry him on his shoulders into Orléans, 'and so he escaped his ransom'."},
]

SECTIONS = [
    {"id": "arrival", "zk": "Orl. Arrival", "titel": "The letter, the arrival and the insults (March–April 1429)",
     "blurb": "How the English received her letter, her entry into the city by torchlight, and the exchange of threats over the herald they had kept.",
     "units": ARRIVAL},
    {"id": "tourelles", "zk": "Orl. Tourelles", "titel": "The Tourelles and the raising of the siege (7–8 May 1429)",
     "blurb": "The wound and the renewed assault, the fall of the Tourelles and the drowning of Glasdale's men, and the Sunday on which she forbade the French to attack.",
     "units": TOURELLES},
]
